version: '3.8'

services:
  registry:
    image: registry:2
    networks:
      - internal
    volumes:
      - registry-data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry

networks:
  internal:
    external: true

volumes:
  registry-data:
