version: "3.8"

services:
  webhook:
    build: ./webhook
    image: ghcr.io/gmunguia/gitops/webhook
    environment:
      BRANCH_NAME: "master"
      GITHUB_REPO: "https://github.com/gmunguia/homelab.git"
      GITHUB_WEBHOOK_SECRET_SECRET_FILE: /run/secrets/github_webhook_secret
      IMAGE_REGISTRY_URL: 127.0.0.1:5000
      NODE_ENV: "production"
      PORT: 4000
      STACKS_FOLDER: "stacks"
    volumes:
      - webhook-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    secrets:
      - github_webhook_secret
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

  tunnel:
    build: ./tunnel
    image: ghcr.io/gmunguia/gitops/tunnel
    environment:
      CLOUDFLARE_TOKEN_SECRET_FILE: /run/secrets/cloudflare_token
    networks:
      - internal
    secrets:
      - cloudflare_token
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

  registry:
    image: registry:2
    networks:
      - internal
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    deploy:
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

networks:
  internal:
    external: true

volumes:
  webhook-data:
  registry-data:

secrets:
  github_webhook_secret:
    external: true
  cloudflare_token:
    external: true
