version: "3.8"

services:
  webhook:
    image: ghcr.io/gmunguia/gitops/webhook:$IMAGE_TAG
    environment:
      BRANCH_NAME: "master"
      GITHUB_REPO: "https://github.com/gmunguia/homelab.git"
      GITHUB_WEBHOOK_SECRET_SECRET_FILE: /run/secrets/github_webhook_secret
      IMAGE_REGISTRY_URL: 127.0.0.1:5000
      NODE_ENV: "production"
      PORT: 4000
      STACKS_FOLDER: "stacks"
    volumes:
      - webhook-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - internal
    secrets:
      - github_webhook_secret
    deploy:
      mode: replicated
      replicas: 2

  tunnel:
    image: ghcr.io/gmunguia/gitops/tunnel:$IMAGE_TAG
    environment:
      CLOUDFLARE_TOKEN_SECRET_FILE: /run/secrets/cloudflare_token
    networks:
      - internal
    secrets:
      - cloudflare_token
    deploy:
      mode: global

  registry:
    image: registry:2
    networks:
      - internal
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    deploy:
      mode: replicated
      replicas: 1

  monitor:
    image: ghcr.io/gmunguia/gitops/webhook:$IMAGE_TAG
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/var/log:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    ports:
      - "8686:8686"
      - "514:514/udp"
    environment:
      - AXIOM_TOKEN_FILE=/run/secrets/axiom_token
      - PROCFS_ROOT=/host/proc
      - SYSFS_ROOT=/host/sys
    secrets:
      - axiom_token
    network_mode: host
    pid: host

networks:
  internal:
    external: true

volumes:
  webhook-data:
  registry-data:

secrets:
  github_webhook_secret:
    external: true
  cloudflare_token:
    external: true
  axiom_token:
    external: true
